language: node_js
sudo: true
node_js:
- stable
cache:
  directories:
  - node_modules
script:
- npm test
- npm run build
deploy:
  provider: gae
  keyfile: gae.json
  project: cinebot
  skip_cleanup: true
  on:
    branch: master
before_install:
- openssl aes-256-cbc -K $encrypted_c86e323467fd_key -iv $encrypted_c86e323467fd_iv
  -in gae.json.enc -out gae.json -d
